# permissions for end users to view guestbook2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guestbook2-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - guestbook2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - guestbook2s/status
  verbs:
  - get
