# permissions for end users to view guestbook3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guestbook3-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - guestbook3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - guestbook3s/status
  verbs:
  - get
